name: CI
on:
  workflow_dispatch:
  push:
  schedule:
    # Run this every day
    - cron: '0 * * * *'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/unstable
          sudo apt-get -y update
          sudo apt-get -y install doxygen luajit neovim python3-msgpack
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: neoconf.nvim
          demojify: true
      - name: Build
        run: |
          nvim -u NONE -E -R --headless --cmd "set rtp^=." --cmd "packloadall" --cmd "luafile lua/neoconf/build/init.lua" --cmd q
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc, schemas and annotations"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
