[selene]
base = "lua51"
name = "selene_vim"

[vim]
any = true

[[Describe.args]]
type = "string"
[[Describe.args]]
type = "function"

[[It.args]]
type = "string"
[[It.args]]
type = "function"

[[Expect.args]]
type = "any"

[Which]
any = true
